# Generated by Django 3.2.4 on 2021-06-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
