# Generated by Django 3.2.4 on 2021-06-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialForm', '0002_form_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='file',
        ),
    ]
