# Generated by Django 3.2.4 on 2021-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialForm', '0003_remove_form_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
