# Generated by Django 3.2.4 on 2021-06-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialForm', '0004_form_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='files',
        ),
    ]
