# Generated by Django 3.2.4 on 2021-06-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialForm', '0005_remove_form_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('user', 'title')},
        ),
    ]
