# Generated by Django 3.2.4 on 2021-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialForm', '0006_auto_20210622_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='summary',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
