# Generated by Django 3.2.4 on 2021-06-23 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialForm', '0008_alter_form_created_at'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='form',
            index_together={('user', 'title')},
        ),
    ]
